name: Publish To Test

on:
  workflow_dispatch:
  
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: eu-central-1
  AWS_DISTRIBUTION_ID: ${{ secrets.TEST_AWS_DISTRIBUTION_ID }}
  AWS_BUCKET_NAME: ${{ secrets.TEST_AWS_BUCKET_NAME }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup mdBook
      uses: peaceiris/actions-mdbook@v1
      with:
        mdbook-version: 'latest'

    - name: build
      run: mdbook build

    - name: Sync files to S3
      run: aws s3 sync ./book/ s3://$AWS_BUCKET_NAME --acl public-read --delete --cache-control max-age=604800

    - name: Notify CloudFront about the changes
      run: aws cloudfront create-invalidation --distribution-id ${AWS_DISTRIBUTION_ID} --paths "/*"
